### ISSUE TITLE
URL changes to actual URL and removes localhost while recording

### ISSUE THREAD

**Issue by rudrathkr** [wiremock/wiremock#1511]
The URL is overwritten while recording tests while navigating to sites(with a link click) 
1. Start the server and start recording
java -jar wiremock-jre8-standalone-2.28.0.jar --enable-browser-proxying --https-port 8888 --proxy-all="https://www.eclipse.org" --record-mappings
2. Do the proxy setting as mentioned in link: I have done the browser configs as mentioned in screenshots:
https://masonm.github.io/wiremock/docs/proxying
3. Go to Site https://localhost:8888, the home page opens which is fine
4. Navigate to some link : Projects
5. Notice the change in URL to remove the word localhost, it is not going via localhost

Is there any steps i am missing. 

PS: This works on some websites(Spring.io) and does not work on some sites. 

Thanks

**Comment by tomakehurst** [comment]
This isn't an issue with WireMock - it's simply that eclipse.org links are all absolute i.e. `https://www.eclipse.org/projects/` rather than just `/projects/`.

This means that regardless of whether you load the homepage from localhost or anywhere else, you'll always go to the actual eclipse.org site when you click that link.

You can work around this using browser proxying however. You'll need to follow the instructions about importing and trusting WireMock's CA cert and start WireMock like this:

```
java -jar wiremock-jre8-standalone-2.28.0.jar --root-dir eclipse-recording --enable-browser-proxying --record-mappings
```

Configure your system proxy to use WireMock - localhost:8080 in this case.

Do some browsing.

Then stop WireMock and start it this way for playback:
```
java -jar wiremock-jre8-standalone-2.28.0.jar --root-dir eclipse-recording --enable-browser-proxying
```
