### ISSUE TITLE
Transformer Parameters do not resolve helpers before modifying response.

### ISSUE THREAD

**Issue by aaron-goff** [wiremock/wiremock#1554]
When trying to use Transformer Parameters and helpers, the helpers do not resolve before the parameter values are used to modify the response. For example...

Mapping file:
```json
{
  "request": {
    "method": "POST",
    "url": "/test"
  },
  "response": {
    "status": 200,
    "bodyFileName": "test.xml",
    "headers": {
      "Content-Type": "application/xml;charset=UTF-8"
    },
    "transformers": ["response-template"],
    "transformerParameters": {
      "test": "{{xPath request.body '/value/text()'}}"
    }
  }
}

```

Request
```xml
...
<value>myRequestValue</value>
...
```

Response file
```xml
...
<value>{{parameters.test}}</value>
...
```

If I change the `test` transformerParameter value to something that doesn't need to be resolved (say, "my value"), then I see that value in the returned response. If I use the xpath helper in another part of the response definition (such as bodyFileName), it resolves correctly. Only when using the helpers as a transformerParameter's value are the helpers + parameters not combining correctly. Instead, the response value would look something like...

```xml
...
<value>{{xPath request.body '/value/text()'}}</value>
...
```
(The string is actually encoded but I'm being lazy -- the important part is that it is the helper that is inserted instead of the resolved helper value.)
This happens with all helpers as best as I can tell.

**Comment by tomakehurst** [comment]
Handlebars doesn't render template fragments passed as variables (I think it's considered risky, since the variables could come from an untrusted source). You can register partials programmatically with the template engine, but that's not much use here unfortunately.

WireMock explicitly applies templating to the following fields: headers, proxy URL, body file name and body, which is why these work when you insert template strings.

I don't think there's a straightforward way to do this while still lazily evaluating the template (and therefore getting the request model in the context).

Is there a way you could work round this e.g. by putting conditional logic in there, switched on the value of the template parameter?
There are some new conditional helpers in 2.29.0 that may make this easier than previously.

**Comment by aaron-goff** [comment]
I think for the use case described, the easiest workaround is to just use a custom transformer to parse out the info from the request and apply it to the response or switch from using `bodyFileName` to just `jsonBody` (and applying the helpers in there without transformerParameters.) I was just seeing this as a nice feature request to simplify things (and since I've seen this issue encountered by a few different people on SO)

Can you elaborate on the new helpers in 2.29.0?

**Comment by tomakehurst** [comment]
Check out the docs for `contains`: http://wiremock.org/docs/response-templating/#contains-helper

and `matches`: http://wiremock.org/docs/response-templating/#matches-helper

**Comment by desmondtsang** [comment]
I'm running into this exact case here - Do Handlebars now render template fragments before substituting transformerParameters?
