### ISSUE TITLE
Enforce consistent code format

### ISSUE THREAD

**Issue by jamietanna** [wiremock/wiremock#1559]
I've noticed that there are a few places in the codebase (i.e. [`FileSource`](https://github.com/tomakehurst/wiremock/blob/d62c457e71e6f66a5120139d9cb93d35d2622cc5/src/main/java/com/github/tomakehurst/wiremock/common/FileSource.java#L24-L35)) which use inconsistent code style.

Would you be happy with an enforced code style, perhaps via the [Spotless Gradle plugin](https://github.com/diffplug/spotless/tree/HEAD/plugin-gradle), which allows folks to easily apply code style changes through `./gradlew spotlessApply`, instead of needing any other local setup?

If so, are there any preferences you would have? I.e. are you happy with Google Java code style, or would another style be preferable?

**Comment by tomakehurst** [comment]
It's been on my list for a while to think about this.

I'm not really a fan of heavy-handed code style enforcement in the build as I find you can end up fighting it when you want a little discretion.

But having said that enforcing a few basics, in particular indentation and brace placement would make merging PRs a hell of a lot easier so perhaps we can start there rather than enforcing a full code style?

**Comment by jamietanna** [comment]
That's interesting - are there any cases where you would see i.e. Google Java code style not being suitable?

Having used differing code styles over the years, I've got to the point where I'd rather have something consistent that takes away any choice from the implementer, and just keeps things consistent

But I get your point, and as you're gonna be working with the code the most, your opinion is most important :grinning: 

It could be the [eclipse-jdt configuration](https://github.com/diffplug/spotless/tree/HEAD/plugin-gradle#eclipse-jdt) is best as it'll provide you the opportunity to hand-craft the required code style you'd like?

**Comment by tomakehurst** [comment]
I don't think there's anything unsuitable in the Google code style specifically. It's just that my memory of working on projects where there's build-time enforcement is that it's like having an overly pedantic teammate nagging you about trivia.

But I also get your point, and TBH the priority should be making it as easy as possible for others to contribute, rather than my own foibles.

If you're happy to open a PR with the Google style enforced, then we can take a look. I guess the clincher might be whether it's going to take days/weeks of work to make the codebase compliant.

**Comment by jamietanna** [comment]
Thanks Tom! I've rasied #1563 for this - fortunately Spotless allows it to be really straightforward to get set up, and to apply against the codebase.

This _will_ cause a lot of conflicts for folks who've already got branches/PRs open - unfortunately I don't have a good suggestion for how to manage this so well :disappointed:

So the current codebase can be up-to-date easily, but the difficulty will be on folks who've got open contributions.

**Comment by tomakehurst** [comment]
Thanks for this.

Agree that existing PRs are going to be a bit of a nightmare so I'm going to park this until I've got 2.29.1 released, then probably try and merge the PRs I think are a priority before pulling the pin out of the grenade.

**Comment by jamietanna** [comment]
Sounds like a plan - I'll mark the PR as a draft for now then

**Comment by jamietanna** [comment]
Sounds like a plan - I'll mark the PR as a draft for now then

**Comment by tomakehurst** [comment]
This might help: https://github.com/diffplug/spotless/tree/main/plugin-gradle#ratchet

**Comment by jamietanna** [comment]
Sorry looks like my reply didn't send - we certainly can do it with ratcheting - I was thinking going for a "big bang" approach would mean some merge conflicts now, but it's reduced soon, whereas ratchet will slowly bring the changes in and folks may have style-related merge conflicts for some time.

It's a balance - sorry for not raising it as I had considered it, and my personal preference is "big bang". What do you think?

**Comment by tomakehurst** [comment]
I tend to lean towards doing most things iteratively, so I think I'd prefer the ratcheting approach. It would also be an opportunity for me to get used to working with it without 100% committing up front. Ratcheting doesn't preclude going all-in at some point, but it's harder to back out if you've taken the big bang approach.

**Comment by jamietanna** [comment]
That makes sense ☺ in which case, the PR should be ready to review when you get a chance!
