### ISSUE TITLE
#1613 breaks EqualToJsonPattern when using Float/Double.

### ISSUE THREAD

**Issue by Choobz** [wiremock/wiremock#1779]
## Bug reports
Wiremock Version : 2.32.0 (no issue in 2.31.0)

Since #1613 any float number ending with .0 is interpreted as a BigDecimal having a scale = 0. Meaning 123.0 is deserialised as 123. (= actual)

Using a basic ObjectMapper, any JsonNode created using 123.0 does register its value as 123.0. (= expected)

The following instruction then fails : [RequestPattern.thatMatch(requestPattern, this.customMatchers)](https://github.com/wiremock/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/verification/InMemoryRequestJournal.java#L58)
`
JSON documents are different:
Different value found in node "floatValue", expected: <123.0> but was: <123>.
`

The body in the request is `123.0`.

Additionally,  when returning the difference to the user the same objectMapper is used to transform the expected JsonNode into a String, meaning no difference between expected and actual is reported to the user (both display 123 instead of the true value 123.0). Quite confusing :)

**Comment by Choobz** [comment]
Maybe related to : https://github.com/FasterXML/jackson-databind/issues/1568

**Comment by jmecsei** [comment]
Hi,
I think the problem is in the Json.java file, wiht ObjectMappper's parameters.

If you see this file in version 2.31.0 : [LINK](https://github.com/wiremock/wiremock/blob/2.31.0/src/main/java/com/github/tomakehurst/wiremock/common/Json.java#L38) and in version 2.33.2: [LINK](https://github.com/wiremock/wiremock/blob/2.33.2/src/main/java/com/github/tomakehurst/wiremock/common/Json.java#L41)

As you can see 2 new decimal parameter have been added to the mapper. Here is a little test to demonstrate the differences:

```java
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.Data;

import java.math.BigDecimal;

public class Test {

    @Data
    static class Demo {
        BigDecimal value;
    }

    @org.junit.jupiter.api.Test
    void teszt_parse_with_decimal_config() throws JsonProcessingException {
        //GIVEN
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
        objectMapper.configure(JsonParser.Feature.ALLOW_COMMENTS, true);
        objectMapper.configure(JsonParser.Feature.ALLOW_SINGLE_QUOTES, true);
        objectMapper.configure(JsonParser.Feature.IGNORE_UNDEFINED, true);
        objectMapper.configure(JsonGenerator.Feature.WRITE_BIGDECIMAL_AS_PLAIN, true);
        objectMapper.configure(DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS, true);

        //WHEN
        System.out.println(objectMapper.readValue("""
                        {
                            "value": 12500.0
                        }
                        """, JsonNode.class));

        //THEN
    }

    @org.junit.jupiter.api.Test
    void teszt_parse_without_decimal_config() throws JsonProcessingException {
        //GIVEN
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
        objectMapper.configure(JsonParser.Feature.ALLOW_COMMENTS, true);
        objectMapper.configure(JsonParser.Feature.ALLOW_SINGLE_QUOTES, true);
        objectMapper.configure(JsonParser.Feature.IGNORE_UNDEFINED, true);

        //WHEN
        System.out.println(objectMapper.readValue("""
                        {
                            "value": 12500.0
                        }
                        """, JsonNode.class));

        //THEN
    }
}

```

**Comment by jmecsei** [comment]
This commit add these chages: https://github.com/wiremock/wiremock/commit/6ef156668a25ff9f175a8c11debaa31ca68d0f1c

**Comment by clayembry** [comment]
This bug is breaking test cases for us as we have mocked data that looks like this:
```
{
    "testField": 1.0
}
```

But wiremock is returning the response like this:
```
{
    "testField": 1
}
```

We have some use cases where the client API schema is weakly typed as Object and fields that were previously being deserialized as Double are now being deserialized as Integer which is breaking our tests.

Wiremock should not be changing the type or precision of floating point values that are being mocked.
