### ISSUE TITLE
UX: Prevent fatal failure when passing the Webhooks classpath to the CLI args

### ISSUE THREAD

**Issue by oleg-nenashev** [wiremock/wiremock#2528]
### Proposal

The webhooks extension was moved into the core and enabled by default in #2376, and after it some integration tests fail with `java.lang.NoSuchMethodException: org.wiremock.webhooks.Webhooks.<init>()`, for example in Docker integration tests until https://github.com/wiremock/wiremock-docker/pull/100 . It happens, because the initializer was removed.

To improve the user experiences for those who update top the recent 3.x versions, I suggest the following:

* Create an empty and `@Deprecated` `org.wiremock.webhooks.Webhooks.<init>()` entry point
* When the endpoint is called, log a warning that passing the class name is no longer required and may lead to compatibility issues in the future

**Comment by etrandafir93** [comment]
Hello @oleg-nenashev, I can look into this one if it's still needed.

Basically we need a no-args constructor [here](https://github.com/wiremock/wiremock/blob/master/src/main/java/org/wiremock/webhooks/Webhooks.java). Will I set the final fields as `null`? I guess so, because, as I can see, this instance will be overridden when loading the extensions because of the common key/name `webhook`. 

Also, for logging the warning, should I use this [Notifier](https://github.com/wiremock/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/common/Notifier.java) and add a _warn()_ method here?

**Comment by prithvitewatia** [comment]
Hi @etrandafir93. I think unfortunately we were both working on the same issue. I have already raised a PR for it. 
I think we could use Notifier with info.
